module.exports = {
  loginPage: {
    username: '#loginId',
    password: '[name=password]',
    ssoDD: '#ssoOption',
    btnLogin: '#portalSignIn',
    logo: '.company-logo',
  },
  homePage: {
    titles: '#db-panel-body_9 div.center',
    searchIn: '#search-mb',
    searchDD: '#search-entities',
    searchBox: '.search-text',
    btnGo: '#cc_mainSearch',
    supportRequest: "(//*[contains(text(), 'Support Request')])[4]",
    knowledge: "(//*[contains(text(), 'Knowledge')])[5]",
    orders: "(//*[contains(text(), 'Orders')])[2]",
    parts: "(//*[contains(text(), 'Parts')])[6]",
    products: "(//*[contains(text(), 'Products')])[5]",
    registration: "(//*[contains(text(), 'Registration')])[4]",
    return: "(//*[contains(text(), 'Returns')])[2]",
    warranty: "(//*[contains(text(), 'Warranty')])[3]",
    network: "(//*[contains(text(), 'Network')])[2]",
    btnGoToMenu: '#mainmenu-toggle',
    btnGTM: '[title="Go to Menu"]',
    btnGTMenu: '.gotomenu',
    contentGoToMenu: '#cc_app_menu',
    CXModule: '[data-text="CX Connect"]',
  },
  product360Page: {
    product360:'[href*="/cc/productInfo.html"]',
    aliNumber:'#serialNumber',
    styleNumber:'#model',
    btnSearch:'#getProductInfo',
    DDcreate:'(//*[@id="formGroup"]/button)[1]',
    btnProductRegistration:'#addNewProductRegistration',
    products:'//*[@id="db-panel-body_9"]/div/div[5]/div/a',
  },
  customer360Page: {
    customerID: '#summery > div > div:nth-child(1) > div > p > a',
    products: 'table[id*="yui_3_14_0_1"] tr:nth-of-type(1) input',
    btnCreateSupportRequest: '.createSupportRequest',
    btnEditCustomer: "(//*[contains(text(), 'Edit Customer')])",
  },
  SR_RequestTab: {
    locationType: '#requester_typeCode',
    location: '##requester_code',
    customerName: '.requesterDetails',
    customerAddress: '.requesterlocationName',
    primaryContact: '#requester_extension_extn01Code',
    preferredContactMethod: '#requester_contact_preferredContactMethod',
    requestType: '#entitySubCategory',
    source: '#source',
    servicerLocationType: '#provider_typeCode',
    servicerLocation: '#provider_code',
    servicerContact: '#provider_address_contact_searchField',
    searchServicerLocationIcon: '[data-typeid = provider_typeCode] button',
    searchServicerContactIcon: '#providerBEContact button',
    servicerLocationSearchResult: '[data-yui3-record*="genericSearchModel"]',
    servicerContactSearchResult: '[data-yui3-record*="genericSearchModel"]',
  },

  supportRequestPage: {
    //Save, Submit and Resolved
    saveSR: '#saveServiceOrder',
    submitSR: '#submitSupportRequest',
    SRID: '//span[contains(text(),"SR")]',
    SRStatus: '//span[@id="ServiceOrderStatus"]',
    btnResolved: '#resolution',
    DDresolutionType: '#resolutionType',
    resolutionDescription: '#resolutionDescription',
    btnSaveResolution: '#saveResolution',
    btnRefresh: 'refreshServiceOrder',
  },

  SRTabs:{
    tabRequest: '#tabREQUEST',
    tabProducts: '#tabPRDS',
    tabVisits: '#tabVISITS',
    tabParts: '#tabPRTS',
    tabLabor: '#tabLBR',
    tabOther: '#tabOTHER',
    tabPayment: '#tabPYMTS',
    tabSummary: '#smalllabel_SMRY',
  },

  SR_ProductsTab:{
    serviceType: '#serviceRequests_0_requestType',
    serviceRequestStatus: '#serviceRequests_0_requestStatus',
    concernType: '#serviceRequests_0_product_0_extension_extn04Code',
    concernDetail: '#serviceRequests_0_product_0_extension_extn19Value',
    reasonDetail: '#serviceRequests_0_complaintCode',
    problemDescription: '#serviceRequests_0_causeCode',
    btnExpandProduct: '#editServiceRequestBtn0',
  },

  SR_VisitsTab:{
    btnaddVisit: "//*[contains(text(), 'Add Visit')]",
    repairSiteType: '#serviceRequests_1_repairSiteAddress_type',
    visitRequestStatus: '#serviceRequests_1_requestStatus',
    preferredTime: '[name="preferredTime1"]',
    duration: '[name="duration1"]',
    btnExpandVisit: '#editServiceRequestBtn1'
  },
  SR_LaborTab:{
    SRT: '#serviceRequests_1_labors_0_laborCode',
    SRTSearchIcon:
      '[data-typeid="serviceRequests_1_labors_0_laborType"] button',
    rateTypeSearchIcon: '#serviceRequests_1_labors_0_rateType',
    actualHours: '#laborAmount_actualLaborHrs0',
    adjustedAmount: '#serviceRequests_1_labors_0_laborAmount_adjustedAmount',
    adjustedHours: '#serviceRequests_1_labors_0_laborAmount_adjustedLaborHrs',
    rateType: '#tabALL',
    rateTypeSearchResult: '.yui3-datatable-data tr',
    reasonDD: '#serviceRequests_1_labors_0_extension_extn07Code',
    adjustedTotalAmount: '#serviceRequests_1_labors_0_adjustedTotalAmount',
  },
  SR_PartTab:{ 
    partSearch: '//*[@id="serviceRequests_0_parts_0_partCode"]',
    partSearchIcon: '(//*[@class="btn btn-default"])[6]',
    searchResult:'#smalllabel_ALL',
    partSearchSelect: '//*[@class="yui3-datatable-data"]//td[2]',
    orderCheckbox: '#serviceRequests_0_parts_0_isShipPart',
    saveButton:'(//*[@id="saveServiceOrder"])[2]',
    submitButton: '(//*[@id="submitSupportRequest"])[2]',
    moreDDParts: '(//div/button[@id])[7]',
    successMessage: '#status > div > div > center',
  },
  SR_SummaryTab:{
    totalPartAmount:'(//*[@class="output right"])[2]',
    totalLabourAmount: '(//*[@class="output right"])[3]',
    totalTax: '(//*[@class="output right"])[7]',
    totalAmt: '(//*[@class="output right"])[8]',

  },
  SR_Payment:{
    moreDD: '#formGroup',
    customerPay: '#customerToPay',
    paymentOptions: '#extension_extn03Code',
    btnSubmitPayment: '#submitPayment',
    entityStatus:'#entityStatus',
    currency:'#currencyCode',
    category:'#category',
    paymentFrom:'#payer_name',
    paymentTo:'#payee_name',
    paymentReference:'',
    tablePaymentList:'#itemList',
    paymentSummary: '.refundSummarycard',
    statusMessage:'#status center',
    paymentLink: '//*[contains(text(), "sandbox")]',
    btnClose: '.icon-cross2',
    paymentStatus: '#PaymentStatus',
    paymentID: '//*[contains(text(), "Payment #")]'
  },

  knowledgePage: {
    knowledgeContent: '#current_landingPage label',
    knowledgeManager: '[id="Knowledge Manager"] li',
  },

  CXConnectPage: {
    listModules: '#current_landingPage label',
    moduleImportExport: '[id="Import/Export"] li',
  },

  ImportPage: {
    btnNew: '#action-btns a[href*="/cc/import.html"]',
    ImportPage: '(//span[contains(text(),"Import")])[2]', //'#action-btns .btn-import',
    importStatus: '#ImportTemplateStatus',
    nameField: '#name',
    DDentityType: '#entityType',
    entityTypeOptions: '#entityType option',
    DDavailableMappings: '#jobCode',
    availableMappingsOptions: '#jobCode option',
    importFormat: '#importFormat',
    delimiter: '#delimiterName',
    delimiterOptions: '#delimiterName option',
    hasHeadersCheckbox: '#hasHeaders',
    importSource: '#importSource',
    importSourceOptions: '#importSource option',
    btnBrowse: '#upload',
    btnImport: '(//a[@id="importData"])[2]',
    importConfirmBox: '#dialog button',
    moreDropDown: '#formGroup ul',
    btnAdvSearch: '.advSearch',
    tableSearchResults: '#genericSearch table tbody tr td',
    statusBar: '#status',
    advSearchColumns: '#resultColumns',
    clmvalName: '#resultColumns [value="master_Name"]',
    rightArrow: '#right-arrow',
    leftArrow: '#left-arrow',
    topArrow: '#top-arrow',
  },

  ImportLogPage: {
    tabLog: '#tabLOG',
    nameField: '#templateName',
    mappingName: '#jobName',
    statusField: '.controls #status ',
    statusMessage: '#statusMessage',
    totalRecords: '#recordCount',
    successCount: '#successCount',
    failureCount: '#failureCount',
    tabRecordData: '#tabREC_DATA',
    UploadRecordSearchResults: '#UploadRecordSearchResults',
    tableResults: '#tab-content table',
    entityCode: "//td[contains(@class, 'EntityCode')]",
    logFile: '#logFileURI a',
    tabRecordData: '#tabREC_DATA',
    tableRecordData: '#tab-content table tbody',
  },

  registrationPage: {
    NewButton: '[id="Product Registration"] li',
    ALI: '#productSerial_serialNumber',
    styleField: 'productSerial_model',
    registrationBlox: "(//*[contains(text(), 'Registration')])[4]",
    uploadFile: 'input[type="file"]',
    customerType: '#customer_typeCode',
    customer: '#customer_code',
    customerSearchIcon: '#customers > span > button',
    saveButton: '//div/a[@id="saveProductRegistration"]',
    saveMessage: '#status > div > div > center',
    // registerMessage: "#status > div > div > center",
    warrantyText: '#warrantyDetailsTable',
    registerButton: '//div/a[@id="registerProductRegistration"]',
    registrationNo: '(//span[contains(text(),"Registration")])[2]',
    registrationStatus: '#status > div > div > center',
    moreDD:'#formGroup',
    salesTicket: '#registrationRef',
    customerDeliveryDate: '#customerDeliveryDate',
  },
};
